### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Rhinoz** [berbb/PortAIO-v2#1]
Why is there a v2??? is this going to be a "donator" only section or something to that effect?

**Comment by berbb** [comment]
Hell no. Never a v2.

**Comment by Rhinoz** [comment]
well why a v2 then? do we need this, or is this just another project youll be starting

**Comment by berbb** [comment]
It's a reboot of PortAIO.

**Comment by Rhinoz** [comment]
use this one instead?

**Comment by berbb** [comment]
It'll be highly experimental but this will eventually replace PortAIO.

**Comment by Rhinoz** [comment]
okay cool! looking forward to seeing the end product!!!
