### ISSUE TITLE
I can not update

### ISSUE THREAD

**Issue by KenDubfire** [berbb/PortAIO-v2#10]
have a problem to upgrade, first download the update and could not be updated, try downloading the update again but went the error page not found 
![chrome_2016-10-22_11-35-02](https://cloud.githubusercontent.com/assets/22999492/19620101/c4974b6e-984b-11e6-9a70-ec516150bac6.png)
![portaio-updater_2016-10-22_11-33-39](https://cloud.githubusercontent.com/assets/22999492/19620102/cbcf9be8-984b-11e6-9abc-a3db963cbdae.png)

**Comment by berbb** [comment]
v2 is now open source. Just install common then v2 in the EB loader. You don't need PortAIO Loader anymore.
