### ISSUE TITLE
Compilling error 

### ISSUE THREAD

**Issue by cleberxfranco** [berbb/PortAIO-v2#115]
Compilling error  now o=

**Comment by berbb** [comment]
1. no, no there is not. *YOU* probably didn't listen to what I told you on the first issue you made.
2. do not make a duplicate issue. whenever you make/reply to an issue I get a notification; its annoying.

[!(http://image.prntscr.com/image/e772800958cf424ea0a2c3d7f854c94f.png)]

**Comment by cleberxfranco** [comment]
tnks I did not see sorry
