### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by crazycloak** [berbb/PortAIO-v2#128]
Today like usual i updated all the addons, but portAIO seems to be error on compiling. So i tried to re-install and it still says failed...

**Comment by berbb** [comment]
Should be fixed now.

**Comment by crazycloak** [comment]
thx

**Comment by berbb** [comment]
Then it's on your end.

**Comment by berbb** [comment]
![](http://image.prntscr.com/image/254d5fbe5daa41a3a14dfc74cf8daed8.png)

**Comment by crazycloak** [comment]
Managed to fix it, by removing the current and installing it back.
