### ISSUE TITLE
Damage Indicator

### ISSUE THREAD

**Issue by Matsing** [berbb/PortAIO-v2#129]
Hi Berb, I hope you can make a **Damage Indicator** especially for those champion who need it like Sebby's Twitch, and all sebby's AIO. Thanks.

**Comment by berbb** [comment]
It'll be as a utility.

**Comment by Matsing** [comment]
@berbb and I also think the damage calculator is not working. I just notice twitch doesn't 'E when enemy is killable. Will wait for it to port. Thanks again.
