### ISSUE TITLE
VHR - Vayne script

### ISSUE THREAD

**Issue by kamilmatt** [berbb/PortAIO-v2#133]
Hi, in vayne script she dont use auto "e" i mean condemn, i dont know why, i set "use auto e", " next auto e " etc. but still wont work ;/. 

I hope you will respond rly quick.

Thank you!

**Comment by Acheiro** [comment]
Generally it does use E barely but it is kinda broken. So if anyone has enough time fix it please.

**Comment by kamilmatt** [comment]
@Acheiro Yep

**Comment by berbb** [comment]
Vayne's condemn should work fine. 

Next Auto E isn't working because Asuna disabled it in his own VHR.
