### ISSUE TITLE
Rethought Here. :)

### ISSUE THREAD

**Issue by MediaGithub** [berbb/PortAIO-v2#137]
//     File:  Rethought Series/Rethought Irelia/Loader.cs
//     Copyright (C) 2016 Rethought
// 
//     This program is free software: you can redistribute it and/or modify
//     it under the terms of the GNU General Public License as published by
//     the Free Software Foundation, either version 3 of the License, or
//     (at your option) any later version.
// 
//     This program is distributed in the hope that it will be useful,
//     but WITHOUT ANY WARRANTY; without even the implied warranty of
//     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//     GNU General Public License for more details.
// 
//     You should have received a copy of the GNU General Public License
//     along with this program.  If not, see <http://www.gnu.org/licenses/>.
// 
//     Created: 04.10.2016 7:43 PM
//     Last Edited: 05.10.2016 8:28 PM

If you would be so kind and not remove my copyrights, I'd be very happy. Feel free to redistribute ir/modify it, but all according to the gnu.

**Comment by SupportExTraGoZ** [comment]
GG takedown soon XD

**Comment by berbb** [comment]
@SupportExTraGoZ Not quite, we won't be on Github much longer :)

**Comment by SupportExTraGoZ** [comment]
@berbb :O You finally port to some uploading sites XDD

**Comment by berbb** [comment]
@SupportExTraGoZ Actually, no, something better. :D

**Comment by SupportExTraGoZ** [comment]
@berbb I wanna know :jew:

**Comment by MediaGithub** [comment]
Case solved, can be closed. :)
