### ISSUE TITLE
Valvrare Sharp Yasuo Evade error

### ISSUE THREAD

**Issue by kawolski21** [berbb/PortAIO-v2#15]
![image](https://cloud.githubusercontent.com/assets/22923937/19622856/08d5fa6a-9869-11e6-92d3-e110ccdfb560.png)

**Comment by berbb** [comment]
Fixed.

**Comment by berbb** [comment]
woops* will check it out

**Comment by berbb** [comment]
Should be fine now, though if it comes up again don't worry about it, it shouldn't cause any performance problems.
