### ISSUE TITLE
How to install script ?

### ISSUE THREAD

**Issue by Qyrie22** [berbb/PortAIO-v2#21]
I try to install Nechrito Riven from here : https://github.com/Nechrito/Leaguesharp and when I select "Nechrito Riven" the installation fail :/ How can I install nechrito riven please ?

**Comment by Muse30** [comment]
xD

1. install this first : https://github.com/berbb/PortAIO-Common
2. install this second : https://github.com/berbb/PortAIO-v2

play riven, press shift go to portAIO menu, dual port and seach for nechrito riven there then press F5
