### ISSUE TITLE
Prediction dont working well atm

### ISSUE THREAD

**Issue by ThumpsUpSchmitty** [berbb/PortAIO-v2#23]
thanks for the update to v2 !
i tested it this morning, trying to find the perfect prediction i played Ahri and Orianna in custom games... but all predictions seems broken (casting not immediately, casting wrong position)

**Comment by kawolski21** [comment]
it works perfect with me

**Comment by ThumpsUpSchmitty** [comment]
which script you using for ahri and orianna ?

**Comment by mannysan** [comment]
It's perfect for me, i not have problem

**Comment by ThumpsUpSchmitty** [comment]
what prediction you using ... OKTW seems broken, the common and SDK is just bad, sprediction needs a fix aswell

**Comment by Muse30** [comment]
prediction is really bad with some champions like zilean, orianna, nidalee (ofc lul), anivia Q, diana Q, syndra W & some other long skillshots so yeah untill prediction is fixed I dont recommend using champions like those except for syndra cuz broken

**Comment by mannysan** [comment]
Syndra is Broken!!

**Comment by mannysan** [comment]
OKTW so Broken.
But, SDK i don't teste him
