### ISSUE TITLE
not injecting

### ISSUE THREAD

**Issue by doenutts** [berbb/PortAIO-v2#3]
![both](https://cloud.githubusercontent.com/assets/22140178/19615246/47e1ed58-97b1-11e6-8d5c-b4200b9f693e.png)
I have both ticked but does not inject into league.

**Comment by doenutts** [comment]
Is there any way to fix this problem of not inject

**Comment by Muse30** [comment]
try deleting appdata

**Comment by doenutts** [comment]
I just did a clean delete of appdata and it still did not inject for some reason :(

**Comment by Muse30** [comment]
can you show me the console in game?

**Comment by doenutts** [comment]
yes ill do that right now

**Comment by doenutts** [comment]
![dfdf](https://cloud.githubusercontent.com/assets/22140178/19616378/04dd4ccc-97c6-11e6-94dc-6c323ee32941.png)

**Comment by Muse30** [comment]
message me on discord please https://discord.gg/0zNgmm6ziPDoOfbZ

**Comment by doenutts** [comment]
the link doesn't send me to a private message with you, i am on the portaio discord channel though, I am disco disco disco paxto disco disco

**Comment by doenutts** [comment]
![ffff](https://cloud.githubusercontent.com/assets/22140178/19616483/d9d0f530-97c8-11e6-9ebc-626e902819b6.png)

**Comment by Muse30** [comment]
fixed 👍
