### ISSUE TITLE
Doesn't inject

### ISSUE THREAD

**Issue by Fearboy1** [berbb/PortAIO-v2#33]
Ok, i've installed it.
Now it doesn't inject,

p.s yeah, i checked PORTAIO. it still not working. my ass is burning.

**Comment by Muse30** [comment]
1 - delete appdata and reinstall Elobuddy
2 - install this https://github.com/berbb/PortAIO-Common
3 - then this https://github.com/berbb/PortAIO-v2

**Comment by Fearboy1** [comment]
@Muse30 fixed by myself.
