### ISSUE TITLE
A lot of circles around champion

### ISSUE THREAD

**Issue by Fearboy1** [berbb/PortAIO-v2#34]
![image](https://cloud.githubusercontent.com/assets/6598192/19741823/f3619cba-9bca-11e6-87d9-831aae57429a.png)

**Comment by Muse30** [comment]
o o

**Comment by Fearboy1** [comment]
so... how to disable it?

**Comment by Muse30** [comment]
never seen that before.. which ports are you using

**Comment by Fearboy1** [comment]
@Muse30 it appeared with port aio. had used Surviror Malzahar.

**Comment by Fearboy1** [comment]
@Muse30 
![image](https://cloud.githubusercontent.com/assets/6598192/19745388/15227b1c-9bda-11e6-981a-fccf83b2958b.png)
got again lul

**Comment by Muse30** [comment]
lol.. Ive been using it all day and never seen that so IDK.. maybe berbb knows xd

**Comment by Muse30** [comment]
I think I saw this circles a long time ago.. in portAIO v1 old version

**Comment by Fearboy1** [comment]
@Muse30 i use the latest lul. got this only today

**Comment by Muse30** [comment]
@Fearboy1 yeah I know.. just saying ive seen this before but not with portAIO v2 and I dont remember what it was

**Comment by Fearboy1** [comment]
@Muse30 its really annoying to look at these shitty circles, they are like  obstacle detector, dissappear when you facing wall or something like this,

**Comment by berbb** [comment]
The only place I seen something like this was in our ezEvade, but the circles don't look the same.
![image](http://image.prntscr.com/image/15dd3f80e0d74333981acdd281901355.png)

I've never gotten this issue with any version of PortAIO so I wouldn't jump to conclusions and say it's a problem with PortAIO.

Clear your appdata, try again and make sure you're not running anything else with PortAIO when testing it.

**Comment by Fearboy1** [comment]
@berbb ok, this is because of MoonWalk Evade, i guess.

**Comment by Fearboy1** [comment]
fixed
