### ISSUE TITLE
All Fiora addons

### ISSUE THREAD

**Issue by papoa** [berbb/PortAIO-v2#37]
projectfiora and underratedaio have t value problems,,, (dont know if that makes sense)

and jisuisfiora doesnt load at all,,,, 

Thanks for the amazing work Berbb,,, thanks for the ported addons ,,, 👍

**Comment by TheKushStyle** [comment]
What do you mean by T value problems?
Can you send a screenshot of the console?

**Comment by papoa** [comment]
while I post the photo,,, it says invalid T value,,,

**Comment by rajuritik** [comment]
@TheKushStyle  i got that too jisusis fiora does't load

**Comment by berbb** [comment]
fixed
