### ISSUE TITLE
wheen you have an SDK assembly enabled nothing loads

### ISSUE THREAD

**Issue by BigPhalus** [berbb/PortAIO-v2#4]
i loaded up SDK chalenger aio for caitlyn and the only thing that showed up was the sdk orbwalker (no utilities and the champ assembly wasnt showing however i believe it was loaded) however once i reverted back to a common assembly (oktw) everything came back (the utilities showed up again) .

**Comment by berbb** [comment]
ChallengerSeries fixed.
