### ISSUE TITLE
Menu & Orbwalker

### ISSUE THREAD

**Issue by Banobo** [berbb/PortAIO-v2#5]
Hey, I love this project. 
Could we have the regular #l menu instead of the EB one? I find the #l easier to read and more familiar. 
Also I noticed when I installed port v2 that OKTW's orbwalker didn't inject. EB's orbwalker is worse than OKTW's in my opinion. Thanks again!

**Comment by Muse30** [comment]
1 . nope just close the EB menu every time you press shift.. its the only way
2 . not sure what do you mean because portAIO disables EB orbwalker so you are actually using l# orb
