### ISSUE TITLE
ElLeeSin

### ISSUE THREAD

**Issue by brianzk** [berbb/PortAIO-v2#68]
ElLeeSin not have Insec to mouse position. Really need update. Plis.

**Comment by berbb** [comment]
I'm not going to add something that wasn't in the original script.

**Comment by brianzk** [comment]
http://prntscr.com/d1iq0t

**Comment by berbb** [comment]
https://github.com/AlterEgojQuery/Will-update/blob/master/ElLeeSin/ElLeeSin/InitMenu.cs#L97

**Comment by brianzk** [comment]
Okkk bro ty. You really best!!
