### ISSUE TITLE
Update nechrito riven 

### ISSUE THREAD

**Issue by Qyrie22** [berbb/PortAIO-v2#75]
Can u update nechrito riven please ? (2nd november update)
https://github.com/Nechrito/Leaguesharp

why the port never auto update script ?
thanks

**Comment by berbb** [comment]
The port doesn't auto update the script because we're not L# lmfao. I'll do it later.

**Comment by Qyrie22** [comment]
ho ok :) Thanks

**Comment by Qyrie22** [comment]
it's updated ? :D

**Comment by berbb** [comment]
yes...
