### ISSUE TITLE
Evade or EzEvade?

### ISSUE THREAD

**Issue by GodForm** [berbb/PortAIO-v2#82]
Wich one is better Ported? Lets say, the one that works better and with less bugs right now

**Comment by Matsing** [comment]
Evade.

**Comment by kawolski21** [comment]
EzEvade = You can humanize It And Its A lot better i evade all skillshot after the update
Evade#= u evade Everything except Banwaves ^^

**Comment by Matsing** [comment]
Evade doesn't evade yasuo q 2.
