### ISSUE TITLE
Update script

### ISSUE THREAD

**Issue by Qyrie22** [berbb/PortAIO-v2#91]
Hey it's me again, sorry ^^ I am playing only with this script
Can you update Nechrito Riven ?

https://github.com/Nechrito/Leaguesharp/tree/master/Nechrito%20Riven

Thanks

**Comment by berbb** [comment]
That's already been added....

**Comment by Qyrie22** [comment]
it's not like the official script :/

**Comment by berbb** [comment]
Then sorry? There's nothing I can do with "it's not like the original".

**Comment by Qyrie22** [comment]
Sorry, with the official script all combo are pretty good, a good QAA & AA cancel, with portaio it's not really "fluide", it's about the orbwalk ?

**Comment by berbb** [comment]
Not sure for you, but the combo's are all decent for me.

**Comment by Qyrie22** [comment]
What's Q delay are u using ?
