### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by niko390** [berbb/PortAIO-v2#96]
Today when i started elobuddy it says compiling error so i deleted the script and tried install it again but now it says install failed cuz addon cant compile

**Comment by Qyrie22** [comment]
Same

**Comment by ihavethemoon** [comment]
Same Same

**Comment by cleberxfranco** [comment]
same

**Comment by berbb** [comment]
Relax, EB was updated to 6.22 today, so I had to update PortAIO to EB's latest core updates. Fixed.
