### ISSUE TITLE
Installing "Failed".

### ISSUE THREAD

**Issue by crazycloak** [berbb/PortAIO-v2#97]
As today i accidentally got "compiling error" on the PortAIOv2, so i tried to reinstall from the github. Turns out, i can't (Yes i have already installed the common)?! Any idea what could've been the issue?
![wtf](https://cloud.githubusercontent.com/assets/23372580/20164831/72b8c84c-a73a-11e6-8eb5-25381c7495f5.png)

**Comment by berbb** [comment]
You're on 6.21.
